export { Home } from './Home/Home.jsx'
export { SinglePostPage } from './SinglePost/SinglePostPage.jsx'
export { AddPost } from './AddPost/AddPostPage.jsx'
export { Registration } from './Registration/RegistrationPage.jsx'
export { Login } from './Login/LoginPage.jsx'
